;
; Chapter11.asm
;
; Created: 5/22/2017 11:16:43 PM
; Author : Saeid
; TO PROGRAM THE ATMEGA32 TO 
; RECIVE BYTES OF DATA SERIALLY AND PUT THEM ON PORTB. 
; SET THE BAUD RATE AT 9600, 8BIT DATA, AND 1 STOP BIT.
; USE RECIEVE COMPLETE INTERRUPT INSTEAD OF THE POLLING METHOD.
  
.INCLUDE "M32DEF.INC"
.CSEG
	RJMP MAIN
.ORG URXCaddr
	RJMP URXC_INT_HANDLER
.ORG 40

MAIN:	LDI	R16, HIGH(RAMEND)
		OUT	SPH, R16
		LDI	R16, LOW(RAMEND)
		OUT	SPL, R16
		LDI R16, (1<<RXEN) | (1<<RXCIE)
		OUT	UCSRB, R16
		LDI R16, (1<<UCSZ1) | (1<<UCSZ0)
		OUT UCSRC, R16
		LDI R16, 0x33
		OUT UBRRL, R16
		LDI R16, 0xFF
		SETI
WAIT_HERE:
		RJMP WAIT_HERE
URXC_INT_HANDLER:
		IN R17,UDR
		OUT PORTB, R17
		RETI
	